### ISSUE TITLE
Online book

### ISSUE THREAD

**Issue by florisvdh** [DickBrus/SpatialSamplingwithR#2]
This book is one of my favourites!! Thanks to a talk of Gerard Heuvelink at OpenGeoHub summer school 2021 I discovered this repository.

Just wanting to help with (from the Preface):

> A gitbook version of this book (html files) is available in the github repository [SpatialSamplingwithR](https://github.com/DickBrus/SpatialSamplingwithR/tree/master).

Indeed :+1:, and thanks só much.

Currently one has to download or sync the rather large repo and view this locally. Would it be possible to publish the contents of the `/docs` folder online, so that it would become readable at https://DickBrus.github.io/SpatialSamplingwithR ? How to do this is described more elaborately in https://bookdown.org/yihui/bookdown/github.html, but in this case I think it would just boil down to adding an empty `.nojekyll` file in `/docs` and publish this folder's contents by adjusting a repo setting (Pages -> Source: point to the `/docs` folder of the master branch):

> One approach is to publish your book as a GitHub Pages site from a `/docs` folder on your master branch as described in [GitHub Help.](http://bit.ly/2cvloKV) [...] Then, [...], go to your repository’s settings and under “GitHub Pages” change the “Source” to be “master branch `/docs` folder”. In this case, the `.nojekyll` file has to be in the `/docs` folder.

**Comment by DickBrus** [comment]
Dear Floris,

Thanks for your message. Yes, I wanted to publish  the book on a GitHub Pages site, and besides on bookdwon.org, but it was my intention to wait until I received the comments and edits of the editor of CRC Press. Maybe I will do this before, in the coming weeks. Any comments on the book are highly appreciated!

Best wishes,

Dick

From: Floris Vanderhaeghe ***@***.***>
Sent: Friday, February 4, 2022 5:31 PM
To: DickBrus/SpatialSamplingwithR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DickBrus/SpatialSamplingwithR] Online book (Issue #2)


This book is one of my favourites!! Thanks to a talk of Gerard Heuvelink at OpenGeoHub summer school 2021 I discovered this repository.

Just wanting to help with (from the Preface):

A gitbook version of this book (html files) is available in the github repository SpatialSamplingwithR<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDickBrus%2FSpatialSamplingwithR%2Ftree%2Fmaster&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N2G4wDuaAcGZfKU3Ic38qyzpBMACskEgXXDtZT1fXJo%3D&reserved=0>.

Indeed 👍, and thanks só much.

Currently one has to download or sync the rather large repo and view this locally. Would it be possible to publish the contents of the /docs folder online, so that it would become readable at https://DickBrus.github.io/SpatialSamplingwithR<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdickbrus.github.io%2FSpatialSamplingwithR&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Bh2sX%2BMNwTcdPw0ZwRmITZsHo8InHNRGwtKAz7ZNfKU%3D&reserved=0> ? How to do this is described more elaborately in https://bookdown.org/yihui/bookdown/github.html<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbookdown.org%2Fyihui%2Fbookdown%2Fgithub.html&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HZNFyjFS6Cn737n6cu6Wu1A56QvaF9aTGNfP9mFvhTo%3D&reserved=0>, but in this case I think it would just boil down to adding an empty .nojekyll file in /docs and publish this folder's contents by adjusting a repo setting (Pages -> Source: point to the /docs folder of the master branch):

One approach is to publish your book as a GitHub Pages site from a /docs folder on your master branch as described in GitHub Help.<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fbit.ly%2F2cvloKV&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OF8kdRbIVFXRAnx%2FtaJR8i5jXJetE0TGwoCxguyLmGw%3D&reserved=0> [...] Then, [...], go to your repository’s settings and under “GitHub Pages” change the “Source” to be “master branch /docs folder”. In this case, the .nojekyll file has to be in the /docs folder.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDickBrus%2FSpatialSamplingwithR%2Fissues%2F2&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yZ%2B1do9AdkV5wMFY0EjFvXmhKaktRcc6GW4qC7s0UPY%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABLANODT3LNLHW5MNCV5GA3UZP5MLANCNFSM5NSHO23Q&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3UwOlzDm7H9FesXBBHdNClU%2BHG%2BMLIXc2wziv7r0Q%2Fo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890662072583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mIwGuXZMy10UfsojOioJu8YD0S2L83OQ%2Bb0hcaz01Yk%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890662072583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jQjqtvYZF4R82rW7vZvey%2BG2KI8VCEbMK2dPX4LZXBY%3D&reserved=0>.

**Comment by DickBrus** [comment]
Hi Floris,

The book is now available as GitHub pages.

Regards,

Dick

From: Floris Vanderhaeghe ***@***.***>
Sent: Friday, February 4, 2022 5:31 PM
To: DickBrus/SpatialSamplingwithR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DickBrus/SpatialSamplingwithR] Online book (Issue #2)


This book is one of my favourites!! Thanks to a talk of Gerard Heuvelink at OpenGeoHub summer school 2021 I discovered this repository.

Just wanting to help with (from the Preface):

A gitbook version of this book (html files) is available in the github repository SpatialSamplingwithR<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDickBrus%2FSpatialSamplingwithR%2Ftree%2Fmaster&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N2G4wDuaAcGZfKU3Ic38qyzpBMACskEgXXDtZT1fXJo%3D&reserved=0>.

Indeed 👍, and thanks só much.

Currently one has to download or sync the rather large repo and view this locally. Would it be possible to publish the contents of the /docs folder online, so that it would become readable at https://DickBrus.github.io/SpatialSamplingwithR<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdickbrus.github.io%2FSpatialSamplingwithR&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Bh2sX%2BMNwTcdPw0ZwRmITZsHo8InHNRGwtKAz7ZNfKU%3D&reserved=0> ? How to do this is described more elaborately in https://bookdown.org/yihui/bookdown/github.html<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbookdown.org%2Fyihui%2Fbookdown%2Fgithub.html&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HZNFyjFS6Cn737n6cu6Wu1A56QvaF9aTGNfP9mFvhTo%3D&reserved=0>, but in this case I think it would just boil down to adding an empty .nojekyll file in /docs and publish this folder's contents by adjusting a repo setting (Pages -> Source: point to the /docs folder of the master branch):

One approach is to publish your book as a GitHub Pages site from a /docs folder on your master branch as described in GitHub Help.<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fbit.ly%2F2cvloKV&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OF8kdRbIVFXRAnx%2FtaJR8i5jXJetE0TGwoCxguyLmGw%3D&reserved=0> [...] Then, [...], go to your repository’s settings and under “GitHub Pages” change the “Source” to be “master branch /docs folder”. In this case, the .nojekyll file has to be in the /docs folder.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDickBrus%2FSpatialSamplingwithR%2Fissues%2F2&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yZ%2B1do9AdkV5wMFY0EjFvXmhKaktRcc6GW4qC7s0UPY%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABLANODT3LNLHW5MNCV5GA3UZP5MLANCNFSM5NSHO23Q&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890661916361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3UwOlzDm7H9FesXBBHdNClU%2BHG%2BMLIXc2wziv7r0Q%2Fo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890662072583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mIwGuXZMy10UfsojOioJu8YD0S2L83OQ%2Bb0hcaz01Yk%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdick.brus%40wur.nl%7Cdff8dc975ac44d659cba08d9e7fbbbc9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637795890662072583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jQjqtvYZF4R82rW7vZvey%2BG2KI8VCEbMK2dPX4LZXBY%3D&reserved=0>.

**Comment by florisvdh** [comment]
This is great news :tada: ; thank you so much!!

**Comment by DickBrus** [comment]
Hi Floris,

The link to the book is

https://dickbrus.github.io/SpatialSamplingwithR/

Dick
